# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ddbb181ea8a10af7f9bf5092e4c9906a4732daaa9b955f2b895c30e5836c26c3f5367d96f5f746f6c50ad54394b22b4742962c90561380d7afdd1fba99cc35c2

test:
  secret_key_base: 1b9a5f95cfd4c4ee7edb0e34a09631f9e07766c3f408afee70dbda66a6bd5a2241e4c8e2bf7cc3c9bb600162e8d62c35f02d0010a659df7ee72f8cbb391df03b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
