# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

require './app/models/book.rb'
require './app/models/author.rb'
require './app/models/review.rb'
require './app/models/book_author.rb'

Review.destroy_all
BookAuthor.destroy_all
Author.destroy_all
Book.destroy_all


book_1 = Book.create(title: 'Book 1', publication_year: 1991, pages: 200, cover_image: 'default')
book_2 = Book.create(title: 'Book 2', publication_year: 1992, pages: 400, cover_image: 'default')
book_3 = Book.create(title: 'Book 3', publication_year: 1994, pages: 250, cover_image: 'default')
book_4 = Book.create(title: 'Book 4', publication_year: 1938, pages: 350, cover_image: 'default')
book_5 = Book.create(title: 'Book 5', publication_year: 1936, pages: 150, cover_image: 'default')
book_6 = Book.create(title: 'Book 6', publication_year: 1936, pages: 450, cover_image: 'default')
book_7 = Book.create(title: 'Book 7', publication_year: 1941, pages: 600, cover_image: 'default')
book_8 = Book.create(title: 'Book 8', publication_year: 1947, pages: 670, cover_image: 'default')
book_9 = Book.create(title: 'Book 9', publication_year: 1956, pages: 800, cover_image: 'default')
book_10 = Book.create(title: 'Book 10', publication_year: 1946, pages: 102, cover_image: 'default')
book_11 = Book.create(title: 'Book 11', publication_year: 1952, pages: 900, cover_image: 'default')
book_12 = Book.create(title: 'Book 12', publication_year: 1948, pages: 909, cover_image: 'default')
book_13 = Book.create(title: 'Book 13', publication_year: 1950, pages: 35, cover_image: 'default')
book_14 = Book.create(title: 'Book 14', publication_year: 1936, pages: 590, cover_image: 'default')
book_15 = Book.create(title: 'Book 15', publication_year: 1942, pages: 623, cover_image: 'default')
book_16 = Book.create(title: 'Book 16', publication_year: 1936, pages: 321, cover_image: 'default')

author_1 = book_1.authors.create(name: "Emmie Hayes")
author_2 = book_2.authors.create(name: "Allison Singer")
author_3 = book_3.authors.create(name: "Ethan Grab")
author_4 = book_4.authors.create(name: "Martha Troubh")
author_5 = book_5.authors.create(name: "Megan McMahon")
author_6 = book_6.authors.create(name: "Joe Bob Smith")
author_7 = book_7.authors.create(name: "John Doe")
author_8 = book_8.authors.create(name: "Carrie Doe")
author_9 = book_9.authors.create(name: "Matt Levy")
author_10 = book_10.authors.create(name: "Aaron Hursh")
author_11 = book_11.authors.create(name: "Bria Zanti")
author_12 = book_12.authors.create(name: "Ian Dougals")
author_13 = book_13.authors.create(name: "Erin Williams")
author_14 = book_14.authors.create(name: "Amy Holy")
author_15 = book_15.authors.create(name: "Jennica Stiehl")
author_16 = book_16.authors.create(name: "Jalena Taylor")
author_17 = book_1.authors.create(name: "Paul Kim")
author_18 = book_2.authors.create(name: "Ramiro Vaca")
author_19 = book_3.authors.create(name: "Smitha Hosmani")
author_20 = book_4.authors.create(name: "Michael Karnes")


review_1 = book_1.reviews.create(username: 'User 1', title: 'Review 1', rating: 4, review_text: "This book is great")
review_2 = book_1.reviews.create(username: 'User 2', title: 'Review 2', rating: 1, review_text: "This book is terrible")
review_3 = book_1.reviews.create(username: 'User 3', title: 'Review 3', rating: 3, review_text: "This book is average")
review_4 = book_2.reviews.create(username: 'User 1', title: 'Review 1', rating: 1, review_text: "This book is terrible")
review_5 = book_2.reviews.create(username: 'User 2', title: 'Review 2', rating: 2, review_text: "This book is below average")
review_6 = book_2.reviews.create(username: 'User 3', title: 'Review 3', rating: 3, review_text: "This book is average")
review_7 = book_3.reviews.create(username: 'User 1', title: 'Review 1', rating: 4, review_text: "This book is great")
review_8 = book_3.reviews.create(username: 'User 2', title: 'Review 2', rating: 5, review_text: "This book is amazing")
review_9 = book_3.reviews.create(username: 'User 3', title: 'Review 3', rating: 1, review_text: "This book is terrible")
review_10 = book_4.reviews.create(username: 'User 1', title: 'Review 1', rating: 2, review_text: "This book is below average")
review_11 = book_4.reviews.create(username: 'User 2', title: 'Review 2', rating: 2, review_text: "This book is below average")
review_12 = book_4.reviews.create(username: 'User 3', title: 'Review 3', rating: 3, review_text: "This book is great")
review_13 = book_5.reviews.create(username: 'User 1', title: 'Review 1', rating: 1, review_text: "This book is great")
review_14 = book_5.reviews.create(username: 'User 2', title: 'Review 2', rating: 1, review_text: "This book is great")
review_15 = book_5.reviews.create(username: 'User 3', title: 'Review 3', rating: 5, review_text: "This book is great")
review_16 = book_6.reviews.create(username: 'User 1', title: 'Review 1', rating: 3, review_text: "This book is great")
review_17 = book_6.reviews.create(username: 'User 2', title: 'Review 2', rating: 3, review_text: "This book is great")
review_18 = book_6.reviews.create(username: 'User 3', title: 'Review 3', rating: 3, review_text: "This book is great")
review_19 = book_7.reviews.create(username: 'User 1', title: 'Review 1', rating: 4, review_text: "This book is great")
review_20 = book_7.reviews.create(username: 'User 2', title: 'Review 2', rating: 4, review_text: "This book is great")
review_21 = book_7.reviews.create(username: 'User 3', title: 'Review 3', rating: 5, review_text: "This book is great")
review_22 = book_8.reviews.create(username: 'User 1', title: 'Review 1', rating: 1, review_text: "This book is great")
review_23 = book_8.reviews.create(username: 'User 2', title: 'Review 2', rating: 4, review_text: "This book is great")
review_24 = book_8.reviews.create(username: 'User 3', title: 'Review 3', rating: 2, review_text: "This book is great")
review_25 = book_9.reviews.create(username: 'User 1', title: 'Review 1', rating: 4, review_text: "This book is great")
review_26 = book_9.reviews.create(username: 'User 2', title: 'Review 2', rating: 3, review_text: "This book is great")
review_27 = book_9.reviews.create(username: 'User 3', title: 'Review 3', rating: 4, review_text: "This book is great")
review_28 = book_10.reviews.create(username: 'User 1', title: 'Review 1', rating: 5, review_text: "This book is great")
review_29 = book_10.reviews.create(username: 'User 2', title: 'Review 2', rating: 4, review_text: "This book is great")
review_30 = book_10.reviews.create(username: 'User 3', title: 'Review 3', rating: 1, review_text: "This book is great")
review_31 = book_11.reviews.create(username: 'User 1', title: 'Review 1', rating: 4, review_text: "This book is great")
review_32 = book_11.reviews.create(username: 'User 2', title: 'Review 2', rating: 1, review_text: "This book is great")
review_33 = book_11.reviews.create(username: 'User 3', title: 'Review 3', rating: 1, review_text: "This book is great")
review_34 = book_12.reviews.create(username: 'User 1', title: 'Review 1', rating: 4, review_text: "This book is great")
review_35 = book_12.reviews.create(username: 'User 2', title: 'Review 2', rating: 2, review_text: "This book is great")
review_36 = book_12.reviews.create(username: 'User 3', title: 'Review 3', rating: 3, review_text: "This book is great")
review_37 = book_13.reviews.create(username: 'User 1', title: 'Review 1', rating: 4, review_text: "This book is great")
review_38 = book_13.reviews.create(username: 'User 2', title: 'Review 2', rating: 5, review_text: "This book is great")
review_39 = book_13.reviews.create(username: 'User 3', title: 'Review 3', rating: 4, review_text: "This book is great")
review_40 = book_14.reviews.create(username: 'User 1', title: 'Review 1', rating: 1, review_text: "This book is great")
review_41 = book_14.reviews.create(username: 'User 2', title: 'Review 2', rating: 1, review_text: "This book is great")
review_42 = book_14.reviews.create(username: 'User 3', title: 'Review 3', rating: 4, review_text: "This book is great")
review_43 = book_15.reviews.create(username: 'User 1', title: 'Review 1', rating: 2, review_text: "This book is great")
review_44 = book_15.reviews.create(username: 'User 2', title: 'Review 2', rating: 4, review_text: "This book is great")
review_45 = book_15.reviews.create(username: 'User 3', title: 'Review 3', rating: 3, review_text: "This book is great")
review_46 = book_16.reviews.create(username: 'User 1', title: 'Review 1', rating: 4, review_text: "This book is great")
review_47 = book_16.reviews.create(username: 'User 2', title: 'Review 2', rating: 5, review_text: "This book is great")
review_48 = book_16.reviews.create(username: 'User 3', title: 'Review 3', rating: 4, review_text: "This book is great")
